<?php
require('fpdf.php');
require_once 'db.php';

// Detectam regiunea
function detectRegion($lat, $long) {
    if ($lat >= 44.3 && $lat <= 44.6 && $long >= 25.9 && $long <= 26.3) return 'Bucuresti';
    if ($lat >= 44.2 && $lat <= 44.5 && $long >= 25.7 && $long <= 26.1) return 'Ilfov';
    if ($lat >= 46.7 && $lat <= 46.9 && $long >= 23.5 && $long <= 23.7) return 'Cluj';
    return 'Necunoscut';
}

function formatPriority($severity) {
    if ($severity <= 2) return 'Mediu';
    if ($severity <= 4) return 'Ridicat';
    return 'Critic';
}

function formatDate($timestamp) {
    setlocale(LC_TIME, 'ro_RO.UTF-8');
    return strftime('%e %B %Y, ora %H:%M', strtotime($timestamp));
}

if (!isset($_GET['alert_id'])) {
    die("ID alerta lipsa.");
}

$alert_id = (int)$_GET['alert_id'];
$query = "SELECT * FROM alerts WHERE alert_id = $alert_id";
$result = $conn->query($query);

if ($result->num_rows === 0) {
    die("Alerta inexistenta.");
}

$alert = $result->fetch_assoc();

$user_id = $alert['user_id'];
$lat = $alert['latitude'];
$long = $alert['longitude'];
$severity = $alert['severity'];
$timestamp = $alert['created_at'];
$region = detectRegion($lat, $long);

// Autoritate
$authority = "Nicio autoritate activa in regiune";
$auth_result = $conn->query("SELECT name FROM authorities WHERE region = '$region' AND status = 'activ' LIMIT 1");
if ($auth_result && $auth_result->num_rows > 0) {
    $authority = $auth_result->fetch_assoc()['name'];
}

// Cod unic
$datePart = date('Ymd', strtotime($timestamp));
$caseId = "SAFE-" . $datePart . "-" . str_pad($alert_id, 3, '0', STR_PAD_LEFT);

// Init PDF
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Helvetica', '', 12);

// Logo + titlu
$pdf->Image('LOGO SAFEALERT.png', 80, 10, 50);
$pdf->Ln(50);
$pdf->SetFont('Helvetica', 'B', 14);
$pdf->Cell(0, 10, 'Formular generat automat - SafeAlert', 0, 1, 'C');
$pdf->Ln(10);

// Informatii principale
$pdf->SetFont('Helvetica', '', 12);
$pdf->SetTextColor(0);

$pdf->Cell(60, 8, 'Location (Locatie):');
$pdf->SetFont('Helvetica', 'B', 12);
$pdf->Cell(0, 8, "GPS Detected: Regiune $region, Coordonate $lat, $long", 0, 1);
$pdf->Ln(2);

$pdf->SetFont('Helvetica', '', 12);
$pdf->Cell(60, 8, 'Case ID (Cod unic):');
$pdf->SetFont('Helvetica', 'B', 12);
$pdf->Cell(0, 8, $caseId, 0, 1);
$pdf->Ln(5);

// Detalii
$pdf->SetFont('Helvetica', '', 12);
$pdf->Cell(0, 8, 'Details of the situation (Detalii):', 0, 1);
$pdf->SetFont('Helvetica', '', 11);
$detalii = "Utilizatorul '$user_id' a activat un cod secret in aplicatie.\n";
$detalii .= "Prioritatea identificata este '" . formatPriority($severity) . "'.\n";
$detalii .= "Alerta asociata automat cu autoritatea: $authority.";
$pdf->MultiCell(0, 8, $detalii);
$pdf->Ln(5);

// Data si ora
$pdf->SetFont('Helvetica', '', 12);
$pdf->Cell(60, 8, 'Date and Time:');
$pdf->SetFont('Helvetica', 'B', 12);
$pdf->Cell(0, 8, formatDate($timestamp), 0, 1);
$pdf->Ln(2);

// Prioritate
$pdf->SetFont('Helvetica', '', 12);
$pdf->Cell(60, 8, 'Priority (Prioritate):');
$pdf->SetFont('Helvetica', 'B', 12);
$pdf->Cell(0, 8, formatPriority($severity), 0, 1);

// Footer
$pdf->SetY(260);
$pdf->SetFont('Helvetica', 'I', 10);
$pdf->Cell(0, 10, 'Generated by SafeAlert System | Confidential document', 0, 0, 'C');

// Download
$pdf->Output('D', "$caseId.pdf");
exit;
